### ISSUE TITLE
课程下载不成功

### ISSUE THREAD

**Issue by lenngennd** [yumueat/TcCourse_downloader#2]
账号内付费课程下载不成功，请问支持账号内付费课程下载吗？

PS D:\TcCourse_downloader> python downloader.py
请选择下载方式:
0.单一视频下载 1.整个课程下载
0
请输入视频的播放网址:https://ke.qq.com/webcourse/****
检测到cookie
检测到有以下码率可供选择，请选择要下载的资源(网络原因可能导致某些码率下载不了，此时会选择尽可能高的码率下载)

0. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=139005,RESOLUTION=498x270
1. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=236146,RESOLUTION=888x480
2. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=379270,RESOLUTION=1332x720
3. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=261176,RESOLUTION=1344x726
3
成功拿到key
21规范01 开课准备及复习要点（1） 的下载进度:   ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋ 100.0%21规范01 开课准备及复习要点（1） 下载完成
21规范01 开课准备及复习要点（1） 的解密进度:   ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋ 100.0%21规范01 开课准备及复习要点（1） 解密完成
命令语法不正确。
21规范01 开课准备及复习要点（1） 合并转换完成
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000188E211CB80>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
PS D:\TcCourse_downloader> node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Users\XXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\XXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:67:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\XXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\XXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:108:22)
    at CRBrowserContext.<anonymous> (C:\Users\XXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\browserContextDispatcher.js:107:81)
    at CRBrowserContext.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

还有这种提示

PS D:\TcCourse_downloader> python downloader.py
请选择下载方式:
0.单一视频下载 1.整个课程下载
0
请输入视频的播放网址:https://ke.qq.com/webcourse/1*****
检测到cookie
检测到有以下码率可供选择，请选择要下载的资源(网络原因可能导致某些码率下载不了，此时会选择尽可能高的码率下载)

0. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=139005,RESOLUTION=498x270
1. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=236146,RESOLUTION=888x480
2. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=379270,RESOLUTION=1332x720
3. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=261176,RESOLUTION=1344x726
3
成功拿到key
21规范01 开课准备及复习要点（1） 的下载进度:   ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋ 100.0%21规范01 开课准备及复习要点（1） 下载完成
21规范01 开课准备及复习要点（1） 的解密进度:   ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋ 100.0%21规范01 开课准备及复习要点（1） 解密完成
命令语法不正确。
21规范01 开课准备及复习要点（1） 合并转换完成

**Comment by yumueat** [comment]
正如README文件里面说的，可以下载账号可以播放的视频，也就是说不能白嫖，付费课程只要是你购买了，在网页上用账号可以播放的，那么用这个脚本获取对应账号的cookie就可以进行下载

**Comment by lenngennd** [comment]
> 正如README文件里面说的，可以下载账号可以播放的视频，也就是说不能白嫖，付费课程只要是你购买了，在网页上用账号可以播放的，那么用这个脚本获取对应账号的cookie就可以进行下载

我自己买的课程，对应账号的cookie，能下载，但是最后不能成功，提示如上。

**Comment by yumueat** [comment]
就这个返回信息来看，你这两个视频是下载好了的，如果是这个课程后面还有视频需要下载，但是出错了，可以考虑重启，上面等等报错理论上不影响程序的执行，下载课程后面的文件可以考虑按照README文件里面的方法修改flag进行下载控制，如果还有其他情况，可以考虑把图片发出来

**Comment by yumueat** [comment]
先查看一下文件夹看看是否成功下载

**Comment by lenngennd** [comment]
> 先查看一下文件夹看看是否成功下载

没有下载成功，没有视频文件

过程中downloads里面有ts文件，最后报错就消失了。

**Comment by yumueat** [comment]
如果重新运行程序还是不行，可以考虑试试单个视频下载

**Comment by lenngennd** [comment]
> 如果重新运行程序还是不行，可以考虑试试单个视频下载

尝试了好多次，只下载成功了两个文件，还是不太会用这个程序。

每次都能下载到TS文件，总是到最后合成解密的时候失败。

**Comment by lenngennd** [comment]
> > 如果重新运行程序还是不行，可以考虑试试单个视频下载
> 
> 尝试了好多次，只下载成功了两个文件，还是不太会用这个程序。
> 
> 每次都能下载到TS文件，总是到最后合成解密的时候失败。

**Comment by yumueat** [comment]
你可以提交出现问题的课程的cid或者链接给我，我来分析一下·

**Comment by lenngennd** [comment]
> 你可以提交出现问题的课程的cid或者链接给我，我来分析一下·

cid=167373

**Comment by yumueat** [comment]
我修改了utils.py文件的代码，你可以下载修改后的代码试试（因为我这边没买课我试不了），先下载视频 规范01 开课准备及复习要点 试试

**Comment by lenngennd** [comment]
> 我修改了utils.py文件的代码，你可以下载修改后的代码试试（因为我这边没买课我试不了），先下载视频 规范01 开课准备及复习要点 试试

谢谢大侠 单个视频可以下载了  课程还是下载不了

有的还是不能成功提示命令行太长

**Comment by lenngennd** [comment]
检测到cookie
检测到有以下码率可供选择，请选择要下载的资源(网络原因可能导致某些码率下载不了，此时会选择尽可能高的码率下载)

0. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=592474,RESOLUTION=752x480
1. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1116790,RESOLUTION=1130x720
2. #EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=2147515,RESOLUTION=1696x1080
1
成功拿到key
22规范-3 建筑结构设计总则3（1） 的下载进度:   ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋ 100.0%22规范-3 建筑结构设计总则3（1） 下载完成
22规范-3 建筑结构设计总则3（1） 的解密进度:   ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋ 100.0%22规范-3 建筑结构设计总则3（1） 解密完成
命令行太长。
22规范-3 建筑结构设计总则3（1） 合并转换完成
PS D:\TcCourse_downloader-main>

**Comment by yumueat** [comment]
应该是文件过大导致的，我更新了utils.py文件，你可以下载修改后的代码试试

**Comment by lenngennd** [comment]
> 应该是文件过大导致的，我更新了utils.py文件，你可以下载修改后的代码试试

已复制         1 个文件。
x197.ts
199.ts
已复制         1 个文件。
x198.ts
200.ts
201.ts
已复制         1 个文件。
x199.ts
磁盘空间不足。
已复制         0 个文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的文件。


执行速度缓慢 最后失败 downloads  decrypt文件夹不断变大  最后失败

**Comment by lenngennd** [comment]
更改大文件支持后无法下载成功

**Comment by yumueat** [comment]
有一个小问题，我再次修改了utils.py文件，你可以再试试

**Comment by lenngennd** [comment]
> 有一个小问题，我再次修改了utils.py文件，你可以再试试

刚下载了一个大文件，已经成功。

我再试试整个课程下载。

**Comment by yumueat** [comment]
整个课程下载估计成功不了，我这个只是针对视频的下载脚本，你这个课程里面有其他的资料

**Comment by lenngennd** [comment]
> 整个课程下载估计成功不了，我这个只是针对视频的下载脚本，你这个课程里面有其他的资料

那我就下单个视频吧 谢谢大侠

**Comment by ghost** [comment]
我的是报错这个：
准备及复习要点 解密完成
0.ts
系统找不到指定的路径。
已复制         0 个文件。
规范精讲22年 开课准备及复习要点 合并转换完成
出错0次
然后就是有一个bug：course.json里json串解析出来有所有的课程，但是实际课程-章节文件夹里会少很多

**Comment by ghost** [comment]
我看了代码def ts2mp4(n,video):
    file_name = "0.ts"
    _n = 0
    if n <= 200:
        for i in range(1, n):
            file_name = file_name + f"+{i}.ts"
        os.system("cd decrypt&&copy /b " + file_name + " " + str(video).replace(" ",""))
    else:
        for i in range(1,n):
            file_name = file_name + f"+{i}.ts"
            if i == n-1:
                os.system("cd decrypt&&copy /b " + file_name + " " + str(video).replace(" ", ""))
            if i % 500 == 0:
                os.system("cd decrypt&&copy /b " + file_name + f" x{_n}.ts" )
                file_name = f" x{_n}.ts"
                _n += 1
    # os.system("cd downloads&&del *.ts")
    # os.system("cd decrypt&&del *.ts")
    # os.system("del get_dk")
    print(str(video.stem)+" 合并转换完成")
    
它是复制最终的文件到课程文件夹/章节的  不应该会找不到路径呀

**Comment by ghost** [comment]
建议作者合并MP4这一块考虑用ffmpeg实现

**Comment by adminlove520** [comment]
建议作者合并MP4这一块考虑用ffmpeg实现

**Comment by yumueat** [comment]
关于找不到路径的问题，你可以提交课程cid或者链接，明天我来帮你看看。
关于ffmpeg，一开始确实是打算用这个的，这个比命令行好太多了，可以方便移植，也不用考虑大文件，而且功能更强大，但是因为一些奇怪的原因代码运行不了，不想再花时间去排查错误了，就选择了copy命令

**Comment by ghost** [comment]
cid和他的是一样的,我们是同一个课程；我手动用copy /b试了一次，合并出来的mp4是有问题的，好像不完整；我最近也在改造这个代码呢

**Comment by ghost** [comment]
Traceback (most recent call last):
File "qcourse.py", line 162, in
main()
File "qcourse.py", line 152, in main
asyncio.run(
File "F:\python3.8.5\lib\asyncio\runners.py", line 43, in run
return loop.run_until_complete(main)
File "F:\python3.8.5\lib\asyncio\base_events.py", line 616, in run_until_complete
return future.result()
File "qcourse.py", line 92, in download_selected_chapter
urls = get_download_urls(term_id, file_id, cid=cid)
File "C:\Users\xx\Downloads\qcourse_scripts-main\utils.py", line 281, in get_download_urls
return get_video_url(video_info, video_index, cid=cid, term_id=term_id)
File "C:\Users\xx\Downloads\qcourse_scripts-main\utils.py", line 253, in get_video_url
+ get_token_for_key_url(term_id=term_id, cid=cid)
File "C:\Users\xx\Downloads\qcourse_scripts-main\utils.py", line 236, in get_token_for_key_url
uin=uin, skey=skey, pskey=pskey, plskey=plskey, cid=cid, term_id=term_id
UnboundLocalError: local variable 'uin' referenced before assignment

这是我在测试隔壁qcourse_scripts代码时遇到的一个问题；我一开始以为是uin只是单纯qq号码的，我就把那一块给注掉了，但是走到下载的时候，就开始抛出这个异常，联系作者也没回应呢   你可以给看看嘛

**Comment by yumueat** [comment]
> cid和他的是一样的,我们是同一个课程；我手动用copy /b试了一次，合并出来的mp4是有问题的，好像不完整；我最近也在改造这个代码呢

如果你们是同一个课程，我的建议是选择单个视频下载，因为这个课程里面有视频之外的东西，我这个只是用于视频下载的。
至于你说的json的bug，我大概看了一下json解析出来的数据和网页上的是差不多的。不知道你说的少了很多是指的视频还是所有资料，用这个代码是不能整个·课程下载的，因为我没有对其他的做处理。所以少很多估计是因为下载不了。所以我的建议还是单个视频下载。之前的那位朋友都成功了，应该是没问题的。
至于你说的找不到指定的路径，我这边测试不了，你可以考虑在utils.py文件的ts2mp4函数中设置断点，查看file_name，str(video).replace(" ","")等变量的值变化，或许能找到原因。
根据你的描述，你应该是在合成的时候出现了问题，我的建议是如果你能改造代码，你可以选择用ffmpeg重写合并那一部分的代码。

**Comment by yumueat** [comment]
说的有些啰嗦了，总而言之就是如果你之前是使用的整个课程下载，建议改为单个视频下载试试，如果之前就是单个视频下载失败，可以考虑设置断点调试或者重写部分代码。
